spring:
  application:
    name: chatbot-api
  profiles:
    active: default
  ai:
    ollama:
      base-url: ${OLLAMA_URL}
      chat:
        options:
          model: ${LLM_NAME}
          num-ctx: ${LLM_CONTEXT_WINDOW}
          num_predict: ${LLM_OUTPUT_TOKENS}
          temperature: ${LLM_TEMPERATURE}

app:
  ai:
    system-prompt: ${LLM_SYSTEM_PROMPT}
